import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/sidebar-provider";
import Sidebar from "@/components/sidebar/sidebar";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { ThemeToggle } from "@/components/theme-toggle";import {Toaster} from "@/components/ui/toaster";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <SidebarProvider>
                        <div className="flex flex-col h-screen">
                            <Sidebar />
                            <div className="flex-1 flex flex-col">
                                <Header />
                                <main className="absolute z-10 top-36 w-full flex-1 overflow-y-scroll">{children}</main>
                                <Toaster />
                                <Footer />
                                <div className="fixed bottom-14 right-5 z-50">
                                    <ThemeToggle />
                                </div>
                            </div>
                        </div>
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
